name: intl_example
description: Example of a Flutter app using the intl library services.

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_translation: ^0.18.2

flutter:
  uses-material-design: true
