name: platform_integration
description: Examples for documenting platform integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^12.0.0

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
