name: web_sockets
description: Web Sockets

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
