name: basic_hero_transition
description: Shows how to create a simple or Hero animation using the Hero class directly.

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/flippers-alpha.png
