name: mixed_lists
description: Example for mixed_lists cookbook recipe

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
