name: constraints
description: example for ui/layout/constraints
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ">=2.0.2 <4.0.0"

flutter:
  uses-material-design: true
