name: interactive
description: >
  Sample app from "Adding interactivity", https://flutter.io/docs/development/ui/interactive.
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.2 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
