name: hero_animations
description: Hero animations

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
