name: architectural_overview
description: samples for architectural-overview.md
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2

dev_dependencies:
  flutter_lints: ">=2.0.2 <4.0.0"

flutter:
  uses-material-design: true
