name: key_value
description: Key value

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
