name: passing_data
description: Passing data

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
