name: null_safety_basics
description: Some code to demonstrate null safety.
version: 1.0.0

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.2 <4.0.0"

flutter:
  uses-material-design: true
