name: handling_taps
description: Example on handling_taps cookbook recipe.

environment:
  sdk: ^3.1.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
